#!/bin/bash

tpId=$(xinput list | grep TouchPad | cut -f2 | cut -c1,2,3 --complement)
tpDisabled=$(xinput list $tpId | grep disabled)

#echo $tpId
#echo $tpDisabled

if [ -z "$1" ] #NO argument provided
	then
	if [[ $tpDisabled  ]]
		then
		 # echo Disabled
		xinput set-prop 14 "Device Enabled" 1
		else 
		# echo Enabled
		xinput set-prop 14 "Device Enabled" 0
	fi
	else #Argument provided
	if [ "$1" = 1 ]
		then
		xinput set-prop 14 "Device Enabled" 1
		else
		if [ "$1" = 0 ]
			then
				xinput set-prop 14 "Device Enabled" 0
			else
				echo tptoggle only accepts 0 or 1
		fi
	fi
fi



